### ISSUE TITLE
Create run.py program with three dependencies

### ISSUE THREAD

**Issue by kbedoway** [kbedoway/venv-exercise#1]
**User Story:**

* Persona: 
* Feature: 
* Business value: 

**Tasks:**
- [ ] Create Python program run.py
- [ ] Create virtual environment .venv
- [ ] Activate virtual environment when developing program
- [ ] Program contains three dependencies (installed through pip)
- [ ] All dependencies are used in this program
- [ ] Add .gitignore file

**Acceptance Criteria:**
1. Only works for this program

**Acceptance Tests:**
1. Users should be able to run the program without error
2. All three dependencies should be used in the program
3. Project should ignore the virtual environment folder
